name: admoai
description: "Flutter SDK for AdMoai"
version: 0.1.0
homepage: https://admoai.com
repository: https://github.com/admoai/admoai-flutter

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.3.0
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  flutter_timezone: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
